### ISSUE TITLE
Does the stream been encoding again when saving as ts format?

### ISSUE THREAD

**Issue by Explorare** [rytsikau/ee.Yrewind#3]
It seems that ffmpeg are using GPU resources to encode the stream locally? And I thought the color of the image saved are a little different from what I saw in Chrome. Not sure if it's a color management difference or the color are changed during encoding locally. I've set the format to `TS` and used best quality automatically.

**Comment by rytsikau** [comment]
The saved video is not encoded, but only downloaded from the server. Since YouTube stores two (as far as i can see) formats, 'mp4' and 'webm', Yrewind chooses 'mp4' for resolutions up to 1080 and 'webm' for higher resolutions. Using '-vformat' you can specify which media container to store the video in, but it's still only packed, no re-encoding. There might be color difference due to browser, codecs, graphics card, etc.

Happy New Year! )
