### ISSUE TITLE
Doesn't download the full live stream

### ISSUE THREAD

**Issue by Grenlet** [rytsikau/ee.Yrewind#9]
Thank you so much for this. I have tried a few different downloader and yours was the only one that could download a live stream right from the beginning. 

I have tested on a live stream and everything was working fine. However when the live stream ended, I noticed the downloaded video duration was shorter than the actual live stream. It's not a lot. It's just shorter by 5 seconds. But I was wondering if this can be fixed so it's possible to download the complete live stream?

**Comment by rytsikau** [comment]
Hello!

When doing the next release, I will check. Thanks!

**Comment by rytsikau** [comment]
Hi!

I was unable to reproduce the error you described. To be honest, I get the opposite result - the stream recorded by the program is always a couple of seconds longer than duration displayed in the Youtube studio.

It's possible that the stream you were recording may have been interrupted for a few seconds due to a network error, that resulted in a timing mismatch. Another option: the first or last seconds of this stream were without sound or, conversely, without video.

**Comment by Grenlet** [comment]
Hmm I experienced that issue last week. 

But when I tried to record 2 livestreams today, this issue has been resolved. Thanks for helping to look into this issue!
